######################################################################
# Automatically generated by qmake (3.0) Wed Jan 20 09:29:47 2016
######################################################################

TEMPLATE = app
TARGET = ui
INCLUDEPATH += .

# Input
FORMS += TestUI.ui
SOURCES += main.cpp
